# Generated by Django 2.1.7 on 2019-03-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_notification_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='text_of_notification',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='title_of_notification',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='type_of_notification',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
