# Generated by Django 2.1.7 on 2019-03-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_auto_20190311_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('ERR', 'Error'), ('NEW', 'New event'), ('ADM', 'Tech message')], max_length=3),
        ),
    ]
