# Generated by Django 2.1.7 on 2019-03-11 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20190311_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='Question',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='User',
            new_name='user',
        ),
    ]
