# Generated by Django 2.1.7 on 2019-03-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0010_auto_20190311_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='total_answers',
            field=models.IntegerField(default=0),
        ),
    ]
