# Generated by Django 2.1.7 on 2019-03-11 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0011_question_total_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='description',
            new_name='text',
        ),
    ]
