# Generated by Django 2.1.7 on 2019-03-11 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0012_auto_20190311_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='isBestAnswer',
            field=models.BooleanField(default=False),
        ),
    ]
