# Generated by Django 2.1.7 on 2019-03-11 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_auto_20190311_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='question',
            name='rating',
        ),
    ]
