# Generated by Django 2.1.7 on 2019-03-12 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0015_auto_20190311_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='isBestAnswer',
        ),
        migrations.AddField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
